-
  name: Install and configure MySQL
  hosts: linux
  become: yes
  vars:
    db_name: testdb
    mysql_user_name: root
    mysql_user_password: root  # Установите здесь ваш пароль для root
  tasks:
    - name: Install necessary packages
      vars:
        packages:
          - mc
          - git
          - pkg-config
          - python3-dev
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      when: ansible_os_family == "Debian"
      loop: "{{ packages }}"

    - name: install pip
      apt:
        name:
          - python3-pip
          - libmysqlclient-dev
          - python3-dev  # Необходим для установки mysqlclient
        state: present


    - name: install pip
      apt:
        name: python3-pip
        state: present

    - name: install mysqlclient
      pip:
        name: mysqlclient
        executable: /usr/bin/pip3

    - name: Install MySQL server
      vars:
        packages:
          - mysql-server
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Start MySQL service
      ansible.builtin.service:
        name: mysql
        state: started

    - name: Set root password for MySQL
      community.mysql.mysql_user:
        name: "{{ mysql_user_name }}"
        host: localhost
        password: "{{ mysql_user_password }}"
        login_user: root
        login_password: ''
        state: present
      ignore_errors: yes

    - name: Create database
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_user_password }}"

    #- name: Create MySQL user with privileges
      #community.mysql.mysql_user:
       # name: "{{ mysql_user_name }}"
        #password: "{{ mysql_user_password }}"
        #priv: "{{ db_name }}.*:ALL"
        #state: present
        #login_user: root
        #login_password: "{{ mysql_user_password }}"
