---
- name: Install Docker
  hosts: gitlab
  become: true
  tasks:

  - name: update
    apt:
      update_cache: yes

  - name: install dependes
    apt:
      name: "{{ item }}"
    loop:
      - ca-certificates
      - curl

  - name: add directory
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Скачать Docker GPG ключ!
    get_url:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      dest: "/etc/apt/keyrings/docker.asc"
      mode: '0644'  # Устанавливаем сразу правильные права
      force: yes  # Обновляем файл, если уже существует

  - name: Добавить репозиторий Docker
    lineinfile:
      path: /etc/apt/sources.list.d/docker.list
      line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
      create: yes  # Создать файл, если он не существует

  - name: update
    apt:
      update_cache: yes


  - name: install
    apt:
      name: "{{ item }}"
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

