version: '3.8'

services:
  
  bd:
    image: mysql
    environment:
       MYSQL_ROOT_PASSWORD: zireael
       MYSQL_DATABASE: zabbix
       MYSQL_USER: zabbix
       MYSQL_PASSWORD: zabbix
    volumes:
      - zabsql:/var.lib.mysql

  zabbix_srv_mysql:
    image: zabbix/zabbix-server-mysql:6.0-ubuntu-latest
    environment:
       DB_SERVER_HOST: bd
       MYSQL_USER: root
       MYSQL_PASSWORD: zireael
       MYSQL_DATABASE: zabbix
       DB_SERVER_PORT: "3306"
    ports:
      - "10051:10051"
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:6.0-ubuntu-latest
    environment:
      DB_SERVER_HOST: bd
      MYSQL_USER: root
      MYSQL_PASSWORD: zireael
      MYSQL_DATABASE: zabbix
      ZBX_SERVER_HOST: zabbix
      DB_SERVER_PORT: "3306"
      PHP_TZ: "Europe/Moscow"
    ports:
      - "8880:8080"
      - "8881:80"
      - "8882:8443"

  adminer:
    image: adminer
    ports:
      - "8884:8080"
    depends_on:
      - bd

volumes:
  zabsql:
